/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciadorarquivoscarros.ui;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.mycompany.gerenciadorarquivoscarros.arquivos.CSVService;
import com.mycompany.gerenciadorarquivoscarros.arquivos.FilePersistence;
import com.mycompany.gerenciadorarquivoscarros.arquivos.JSONService;
import com.mycompany.gerenciadorarquivoscarros.arquivos.XMLService;
import com.mycompany.gerenciadorarquivoscarros.classes.Carro;
import com.mycompany.gerenciadorarquivoscarros.classes.ListCarros;
import jakarta.xml.bind.JAXBException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author piva
 */
public class FrCadCarros extends javax.swing.JFrame {
    ListCarros listCarros;
    private boolean editing;
    private String choicedID;
    
    
    /**
     * Creates new form FrCadCarros
     */
    public FrCadCarros(){
        initComponents();
        this.listCarros = new ListCarros();
        this.clearCampos();
        this.enableCampos(false);
        this.editing = false;
        this.choicedID = "";
        try {
            this.saveToList();
        } catch (IOException ex) {
            Logger.getLogger(FrCadCarros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitile = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelOptions = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnCancell = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        painelAtributos = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        edtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        edtModelo = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        edtAno = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        panelListagem = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblTitle.setText("Cadastro de Carros");
        panelTitile.add(lblTitle);

        panelOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnNew.setText("NOVO");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        panelOptions.add(btnNew);

        btnCancell.setText("CANCELAR");
        btnCancell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellActionPerformed(evt);
            }
        });
        panelOptions.add(btnCancell);

        btnEdit.setText("EDITAR");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelOptions.add(btnEdit);

        btnDelete.setText("DELETAR");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelOptions.add(btnDelete);

        btnSave.setText("SALVAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelOptions.add(btnSave);

        lblID.setText("ID");

        lblMarca.setText("Marca");

        edtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMarcaActionPerformed(evt);
            }
        });

        lblModelo.setText("Modelo");

        edtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtModeloActionPerformed(evt);
            }
        });

        lblAno.setText("Ano");

        edtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAnoActionPerformed(evt);
            }
        });

        lblPreco.setText("Preço");

        edtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAtributosLayout = new javax.swing.GroupLayout(painelAtributos);
        painelAtributos.setLayout(painelAtributosLayout);
        painelAtributosLayout.setHorizontalGroup(
            painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtributosLayout.createSequentialGroup()
                .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAtributosLayout.createSequentialGroup()
                        .addComponent(lblMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAtributosLayout.createSequentialGroup()
                        .addComponent(lblModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAtributosLayout.createSequentialGroup()
                        .addComponent(lblAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtAno))
                    .addGroup(painelAtributosLayout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtPreco))
                    .addGroup(painelAtributosLayout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtID)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAtributosLayout.setVerticalGroup(
            painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(edtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(edtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(edtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno)
                    .addComponent(edtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(edtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        panelListagem.setViewportView(edtListagem);
        this.edtListagem.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelListagem)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListagem))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void saveToList() throws FileNotFoundException {
        String path = "Listagem.json";
        String data = FilePersistence.loadFromFile(path);
       
        try {
            //Tranformar os arquivos JSON na lista
            this.listCarros = (ListCarros) JSONService.fromJSON(data);
        } catch (JsonProcessingException ex) {
            Logger.getLogger(FrCadCarros.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (this.listCarros != null) {
            this.edtListagem.setText(this.listCarros.toString());
        } else {
            this.listCarros = new ListCarros();
        }  
    }
    
    private void saveToCSV() throws IOException {
        String path = "ListagemCSV.csv";
        String data;
      
        //Tranformar a lista de carros em CSV
        data = CSVService.toCSV(this.listCarros.getListCarros());
        FilePersistence.saveToFile(data, path);        
    }
    
    private void saveToXML() throws JAXBException, IOException {
        String path = "ListagemXML.xml";
        String data;
        
        //Tranformar a lista de carros em XML
        data = XMLService.toXML(this.listCarros);
        FilePersistence.saveToFile(data, path);
    }
    
    private void saveToJSON() throws IOException {
        String path = "Listagem.json";
        String data;
        
        //Transformar a lista de carros em JSON
        data = JSONService.toJSON(this.listCarros.getListCarros());
        FilePersistence.saveToFile(data, path);
    }
    
    private void clearCampos() {
        this.edtAno.setText("");
        this.edtID.setText("");
        this.edtMarca.setText("");
        this.edtModelo.setText("");
        this.edtPreco.setText("");
    }
    
    private void enableCampos(boolean flag) {
        this.edtAno.setEnabled(flag);
        this.edtID.setEnabled(flag);
        this.edtMarca.setEnabled(flag);
        this.edtModelo.setEnabled(flag);
        this.edtPreco.setEnabled(flag);
    }
    
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.clearCampos();
        this.enableCampos(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void fillEditCampos(Carro carro) {
        this.edtAno.setText(carro.getAno()+"");
        this.edtID.setText(carro.getId());
        this.edtMarca.setText(carro.getMarca());
        this.edtModelo.setText(carro.getModelo());
        this.edtPreco.setText(carro.getPreco()+"");
    }
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        this.choicedID = JOptionPane.showInputDialog("Digite o ID do carro que será editado");
        Carro editedCarro = this.listCarros.findCarroById(this.choicedID);
        this.clearCampos();
        
        if (editedCarro != null) {
            this.editing = true;
            this.enableCampos(true);
            
            this.fillEditCampos(editedCarro);   
        } else {
            this.enableCampos(false);
            JOptionPane.showMessageDialog(this, "Esse carro não foi registrado no sistema");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void edtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMarcaActionPerformed

    private void edtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtModeloActionPerformed

    private void edtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAnoActionPerformed

    private void edtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPrecoActionPerformed

    private void btnCancellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellActionPerformed
        this.clearCampos();
        this.enableCampos(false);
        this.editing = false;
    }//GEN-LAST:event_btnCancellActionPerformed

    private Carro getCampos() {
        Carro carro = new Carro();
        
        if (!this.edtAno.getText().isEmpty()) 
           carro.setAno(Integer.parseInt(this.edtAno.getText()));
        else 
            System.out.println("Ano não encontrado");
        
        carro.setId(this.edtID.getText());
        carro.setMarca(this.edtMarca.getText());
        carro.setModelo(this.edtModelo.getText());
        
        if (!this.edtPreco.getText().isBlank()) 
            carro.setPreco(Double.parseDouble(this.edtPreco.getText()));
        else 
            System.out.println("Preço não encontrado");

        
        return carro;
    }
    
    private void saveFiles() {
        try {
            this.saveToCSV();
        } catch (IOException ex) {
            Logger.getLogger(FrCadCarros.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.saveToXML();
        } catch (JAXBException | IOException ex) {
            Logger.getLogger(FrCadCarros.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.saveToJSON();
        } catch (IOException ex) {
            Logger.getLogger(FrCadCarros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Carro newCarro = this.getCampos();
        
        if (this.editing) {
            this.listCarros.edit(this.choicedID, newCarro);
            JOptionPane.showMessageDialog(this, "Carro editado");
            
            this.edtListagem.setText(this.listCarros.toString());
            this.saveFiles();

        } else {
            if (this.listCarros.findCarroById(newCarro.getId()) == null) {
                this.listCarros.add(newCarro);
                JOptionPane.showMessageDialog(this, "Carro Adicionado!");
                
                this.edtListagem.setText(this.listCarros.toString());
                this.saveFiles();
            } else {
                JOptionPane.showMessageDialog(this, "O ID desse carro já está adicionado");
            }
        }
        
        this.clearCampos();
        this.enableCampos(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        this.clearCampos();
        this.enableCampos(false);
        
        this.choicedID = JOptionPane.showInputDialog("Digite o ID do carro que será removido");
        
        if (this.listCarros.findCarroById(choicedID) != null) {
            this.listCarros.remove(choicedID);
            JOptionPane.showMessageDialog(this, "Carro removido");

            this.edtListagem.setText(this.listCarros.toString());
            this.saveFiles();
        } else {
            JOptionPane.showMessageDialog(this, "Esse carro não foi registrado no sistema");
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancell;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField edtAno;
    private javax.swing.JTextField edtID;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtMarca;
    private javax.swing.JTextField edtModelo;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel painelAtributos;
    private javax.swing.JScrollPane panelListagem;
    private javax.swing.JPanel panelOptions;
    private javax.swing.JPanel panelTitile;
    // End of variables declaration//GEN-END:variables
}
